### ISSUE TITLE
[]string in const causes `scala.NotImplementedError`

### ISSUE THREAD

**Issue by folex** [fluencelabs/aqua#463]
**Code**
```
import "@fluencelabs/aqua-lib/builtin.aqua"

const NODE_ID = "12D3KooWKnEqMfYo9zvfHmqTLpLdiHXPe4SVqUWcWHDJdFGrSmcA"
const VIA_AR = ["12D3KooWKnEqMfYo9zvfHmqTLpLdiHXPe4SVqUWcWHDJdFGrSmcA"]

func viaArr() -> Info:
    on NODE_ID via VIA_AR:
        p <- Peer.identify()
    <- p
```

**How to trigger**
```
 aqua --air -i viaArr.aqua -o /tmp
```

**Error**
```
% aqua --air -i ~/Development/aqua_scripts/viaArr.aqua -o /tmp
2022.03.22 20:31:16 [INFO] Aqua Compiler 0.7.0-285
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(file:///Users/folex/.nvm/versions/node/v17.3.0/lib/node_modules/@fluencelabs/aqua/aqua.js:73226:9)
  at aqua.model.ValueModel$.fromRaw(file:///Users/folex/.nvm/versions/node/v17.3.0/lib/node_modules/@fluencelabs/aqua/aqua.js:62238:20)
  at aqua.model.AquaContext$.fromRawContext(file:///Users/folex/.nvm/versions/node/v17.3.0/lib/node_modules/@fluencelabs/aqua/aqua.js:80881:52)
  at aqua.model.AquaContext$.exportsFromRaw(file:///Users/folex/.nvm/versions/node/v17.3.0/lib/node_modules/@fluencelabs/aqua/aqua.js:81246:15)
  at {anonymous}()(file:///Users/folex/.nvm/versions/node/v17.3.0/lib/node_modules/@fluencelabs/aqua/aqua.js:38518:67)
```

**Comment by DieMyst** [comment]
fixed in #496
